# Generated by Django 6.1 on 2026-08-30 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ("-created_at",)},
        ),
    ]
