# Generated by Django 6.1 on 2026-08-30 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_task_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ("-created_at",)},
        ),
    ]
