# Generated by Django 6.1 on 2026-09-02 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created_at', '-id')},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-created_at', '-id')},
        ),
    ]
