# Generated by Django 6.1 on 2026-08-30 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_activitylog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ("-created_at",)},
        ),
    ]
