# Generated by Django 6.1 on 2026-09-02 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ('-timestamp', '-id')},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ('joined_at', 'id')},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-created_at', '-id')},
        ),
    ]
